"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 06:04:02.643641
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "inactive",
                name="campaign_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("name", name=op.f("uq_channels_name")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("platform", "external_id", name=op.f("uq_sources_platform")),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_targets")),
        sa.UniqueConstraint("code", name=op.f("uq_targets_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "ADVISOR",
                "VIEWER",
                name="user_role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "campaign_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_sources_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_campaign_sources_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_campaign_sources_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_sources")),
        sa.UniqueConstraint(
            "campaign_id", "source_id", name=op.f("uq_campaign_sources_campaign_id")
        ),
    )
    op.create_table(
        "campaign_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_targets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["targets.id"], name=op.f("fk_campaign_targets_target_id_targets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_targets")),
        sa.UniqueConstraint(
            "campaign_id", "target_id", name=op.f("uq_campaign_targets_campaign_id")
        ),
    )
    op.create_table(
        "prospects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("linkedin_id", sa.String(length=255), nullable=True),
        sa.Column("facebook_id", sa.String(length=255), nullable=True),
        sa.Column("instagram_id", sa.String(length=255), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("origin_channel_id", sa.Integer(), nullable=True),
        sa.Column("current_channel_id", sa.Integer(), nullable=True),
        sa.Column(
            "profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "consent_status",
            sa.Enum(
                "unknown",
                "granted",
                "opted_out",
                name="consent_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("consent_source", sa.String(length=100), nullable=True),
        sa.Column("consent_given_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opted_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_channel_id"],
            ["channels.id"],
            name=op.f("fk_prospects_current_channel_id_channels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["origin_channel_id"],
            ["channels.id"],
            name=op.f("fk_prospects_origin_channel_id_channels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
            name=op.f("fk_prospects_target_id_targets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospects")),
        sa.UniqueConstraint("facebook_id", name=op.f("uq_prospects_facebook_id")),
        sa.UniqueConstraint("instagram_id", name=op.f("uq_prospects_instagram_id")),
        sa.UniqueConstraint("linkedin_id", name=op.f("uq_prospects_linkedin_id")),
        sa.UniqueConstraint("phone", name=op.f("uq_prospects_phone")),
    )
    op.create_index(
        "uq_prospects_email_lower", "prospects", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("advisor_id", sa.Integer(), nullable=True),
        sa.Column("calendar_event_id", sa.String(length=255), nullable=True),
        sa.Column("zoom_meeting_id", sa.String(length=255), nullable=True),
        sa.Column("meeting_url", sa.String(length=500), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "scheduled",
                "done",
                "cancelled",
                "no_show",
                name="appointment_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisor_id"],
            ["users.id"],
            name=op.f("fk_appointments_advisor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_appointments_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
        sa.UniqueConstraint("calendar_event_id", name=op.f("uq_appointments_calendar_event_id")),
        sa.UniqueConstraint("zoom_meeting_id", name=op.f("uq_appointments_zoom_meeting_id")),
    )
    op.create_index(
        op.f("ix_appointments_prospect_id"), "appointments", ["prospect_id"], unique=False
    )
    op.create_table(
        "campaign_prospects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_source_id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column(
            "interest_status",
            sa.Enum(
                "cold",
                "warm",
                "hot",
                "very_hot",
                name="interest_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "conversion_stage",
            sa.Enum(
                "new",
                "to_qualify",
                "contacted",
                "in_conversation",
                "qualified",
                "meeting_proposed",
                "meeting_scheduled",
                "meeting_done",
                "applied",
                "converted",
                "to_follow_up",
                "lost",
                name="conversion_stage",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("interest_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fit_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("assigned_advisor_id", sa.Integer(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_advisor_id"],
            ["users.id"],
            name=op.f("fk_campaign_prospects_assigned_advisor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_source_id"],
            ["campaign_sources.id"],
            name=op.f("fk_campaign_prospects_campaign_source_id_campaign_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_campaign_prospects_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_prospects")),
        sa.UniqueConstraint(
            "campaign_source_id",
            "prospect_id",
            name=op.f("uq_campaign_prospects_campaign_source_id"),
        ),
    )
    op.create_index(
        op.f("ix_campaign_prospects_assigned_advisor_id"),
        "campaign_prospects",
        ["assigned_advisor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_prospects_prospect_id"),
        "campaign_prospects",
        ["prospect_id"],
        unique=False,
    )
    op.create_table(
        "consent_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "granted",
                "withdrawn",
                name="consent_event_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_consent_events_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_consent_events_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_events")),
    )
    op.create_index(
        op.f("ix_consent_events_prospect_id"), "consent_events", ["prospect_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "handed_off",
                "closed",
                name="conversation_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_conversations_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_conversations_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_prospect_id"), "conversations", ["prospect_id"], unique=False
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="direction",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=True),
        sa.Column("sentiment", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_interactions_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_interactions_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interactions")),
        sa.UniqueConstraint("channel_id", "external_id", name=op.f("uq_interactions_channel_id")),
    )
    op.create_index(
        "ix_interactions_prospect_created",
        "interactions",
        ["prospect_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "prospect_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("channel_identifier", sa.String(length=255), nullable=False),
        sa.Column("is_preferred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_prospect_channels_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_prospect_channels_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_channels")),
        sa.UniqueConstraint(
            "channel_id", "channel_identifier", name=op.f("uq_prospect_channels_channel_id")
        ),
        sa.UniqueConstraint(
            "prospect_id", "channel_id", name=op.f("uq_prospect_channels_prospect_id")
        ),
    )
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("campaign_prospect_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "executed",
                "cancelled",
                name="follow_up_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_prospect_id"],
            ["campaign_prospects.id"],
            name=op.f("fk_follow_ups_campaign_prospect_id_campaign_prospects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_follow_ups_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_follow_ups_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_ups")),
    )
    op.create_index(
        "ix_follow_ups_status_scheduled", "follow_ups", ["status", "scheduled_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum(
                "prospect",
                "agent",
                "advisor",
                name="sender_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("external_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "external_message_id", name=op.f("uq_messages_conversation_id")
        ),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "score_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prospect_id", sa.Integer(), nullable=False),
        sa.Column("campaign_prospect_id", sa.Integer(), nullable=True),
        sa.Column(
            "score_type",
            sa.Enum(
                "interest",
                "fit",
                "total",
                name="score_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_prospect_id"],
            ["campaign_prospects.id"],
            name=op.f("fk_score_events_campaign_prospect_id_campaign_prospects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_score_events_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_events")),
    )
    op.create_index(
        op.f("ix_score_events_campaign_prospect_id"),
        "score_events",
        ["campaign_prospect_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_events_prospect_id"), "score_events", ["prospect_id"], unique=False
    )
    op.create_table(
        "stage_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_prospect_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_stage",
            sa.Enum(
                "new",
                "to_qualify",
                "contacted",
                "in_conversation",
                "qualified",
                "meeting_proposed",
                "meeting_scheduled",
                "meeting_done",
                "applied",
                "converted",
                "to_follow_up",
                "lost",
                name="stage_event_from",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_stage",
            sa.Enum(
                "new",
                "to_qualify",
                "contacted",
                "in_conversation",
                "qualified",
                "meeting_proposed",
                "meeting_scheduled",
                "meeting_done",
                "applied",
                "converted",
                "to_follow_up",
                "lost",
                name="stage_event_to",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_prospect_id"],
            ["campaign_prospects.id"],
            name=op.f("fk_stage_events_campaign_prospect_id_campaign_prospects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_events")),
    )
    op.create_index(
        op.f("ix_stage_events_campaign_prospect_id"),
        "stage_events",
        ["campaign_prospect_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stage_events_campaign_prospect_id"), table_name="stage_events")
    op.drop_table("stage_events")
    op.drop_index(op.f("ix_score_events_prospect_id"), table_name="score_events")
    op.drop_index(op.f("ix_score_events_campaign_prospect_id"), table_name="score_events")
    op.drop_table("score_events")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_follow_ups_status_scheduled", table_name="follow_ups")
    op.drop_table("follow_ups")
    op.drop_table("prospect_channels")
    op.drop_index("ix_interactions_prospect_created", table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_conversations_prospect_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_consent_events_prospect_id"), table_name="consent_events")
    op.drop_table("consent_events")
    op.drop_index(op.f("ix_campaign_prospects_prospect_id"), table_name="campaign_prospects")
    op.drop_index(
        op.f("ix_campaign_prospects_assigned_advisor_id"), table_name="campaign_prospects"
    )
    op.drop_table("campaign_prospects")
    op.drop_index(op.f("ix_appointments_prospect_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index("uq_prospects_email_lower", table_name="prospects")
    op.drop_table("prospects")
    op.drop_table("campaign_targets")
    op.drop_table("campaign_sources")
    op.drop_table("users")
    op.drop_table("targets")
    op.drop_table("sources")
    op.drop_table("channels")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
